config/loadConfig.go

Turns out we were not properly detecting the root of the filesystem and the fact that it was working at all in most cases was coincidental. This should be more robust and works across all tested platforms.

fix(config): fix for infinite path walking failure when loading .bmx file

---

saml/serviceProviders/aws/mocks/awsServiceProvider.go
saml/serviceProviders/aws/provider_test.go

Resolve a spelling mistake in the `SecretAccessKey` AWS mocks.

chore(spelling): Resolve spelling error in the aws string mocks

---

config/config_test.go
saml/identityProviders/okta/okta.go
saml/identityProviders/okta/okta_test.go

Resolve a series of ineffectual error assignments in the Okta provider.
This was caught by goreportcard-cli, when run against the project. The style of err handling is mirrored by similar if statements in the area.
Catching these errors will need to be bundled into CI at a later date to prevent them from occurring in the future.

fix(ineffassign): Ineffectual assignments of err responses in okta provider

---

.github/workflows/main.yml

Enforce `go fmt` as a requirement for any change to be merged into mainline.
This addresses previous issues identified when scanning the code with goreportcard. Issues with `gofmt` were identified, and this change prevents those kinds of issues from existing in the mainline going forward.

test(format): Enforce formatting guidelines

---

.bazelrc
cmd/bmx/BUILD.bazel
cmd/bmx/version.go
tools/stamp.sh

Stamp the bazel compiled binaries (missing goreleaser binaries) with the version and commit sha.
For debugging purposes it will be good to have a commit sha associated with the binary, so it can referenced back if its an out of date version of `bmx`. For cases that are installed with `go get`, the version will not be stamped, which will yield the `bmx/nostamp` output.

feat(version): Stamp compiled binary with version and commit

---

BUILD
cmd/bmx/BUILD.bazel
cmd/bmx/login.go
login.go
saml/identityProviders/okta/okta.go

Introduce `login` command for creating a new session with Okta.
Sessions are created in the process of executing other commands (e.g. `print`, `credential-process`), while we have no explicit command for creating a new session. This enables an option for creating a session without needing to ignore the response.
This is related to an issue when developing when working in a non-interactive environment. In those cases, we need to login ahead of time to avoid any prompts. At the moment that can be done using `bmx print` and discarding the output (/dev/null).
The command inputs of `login` mirror that of `print` to match the UserInfo API. This can be refactored in future work to reduce the inputs.

feat(cmd-login): Login command for creating Okta sessions

---

cmd/bmx/BUILD.bazel
cmd/bmx/config.go

Emit an ini configuration file for mapping to a Okta organization and user.
This is intended to assist with automated configured of user environments by allowing for bmx to create a simple configuration file for a user. This doesn't do any mappings for other config options like account, which would need to be set by the user. When there is only a single AWS okta app, then bmx should default to selecting that option.
This allows for cases where the machine username matches the okta username, you can run this:
```
bmx config --org 'ACME' --user `id -n -u` > ~/.bmx/config
```
To fill in the details of the organization and user.

feat(cmd-config): Emit default config for user directory

---

console.go
console/ConsoleReader.go
mocks/consoleReader.go
saml/identityProviders/okta/okta.go

Move the option selection from authenticate into its own method.
Authenticate has the logic for terminal option selection bundled into it. This removes that logic from the authenticate into its own `Option` command, with the aim of simplifying the `authenticate` method as a whole. Filtering for the AWS Okta apps have been migrated to the Okta priority level.
Additionally the new feature of selecting first if only one app-link is available.

refactor(authenticate): Generic option selection from authenticate

---

cmd/bmx/credential-process.go
cmd/bmx/login.go
cmd/bmx/print.go
cmd/bmx/write.go
config/loadConfig.go
console.go
credential-process.go
login.go
mocks/mokta.go
print.go
saml/identityProviders/IdentityProvider.go
saml/identityProviders/okta/okta.go
saml/serviceProviders/UserInfo.go
write.go

Set the desired multi-factor type (`push` or `token:software:totp`) for use.
If available, the desired multi-factor type specified in the user configuration will be used when selecting a multi-factor type. If there is only one factor option supplied by Okta, then that factor will be selected by default. This allows for `~/.bmx/config` to contain the following:
```ini
factor = push
factor = token:software:totp
```
Additional refactoring work has been done to leverage `.Option` for the multi-factor selection text, and some of the complexity of `doMfa` has been split out into `selectFactor`. Further refactoring work will be needed to reduce the impact of user config changes.

feat(config-mfa): Set multifactor type in user configuration

---

console/ConsoleReader.go

Print newline after reading password to fix line breaks for prompts.
Any text that follows the password prompt will land on the same line as the password prompt. Visually this can be jarring as it doesn't make it immediately obvious what the next prompt is asking (as its in an odd spot). This resolves this by adding a new line after the password is retrieved.
See below for an example of odd placement.
```
Okta Password:  Available MFA: 
```

fix(console): Print newline after reading password

---

saml/identityProviders/okta/okta.go

When the TOTP challenge is failed, it yields an json error (`json: cannot unmarshal object into Go value of type []okta.OktaAppLink`).
This error is not ideal, as it doesn't exactly explain why the challenge failed. For the reproduced case, this occurs when the provided `TOTP` code is incorrect, and the MFA_CHALLENGE response is re-issued. This resolves the issue by returning a sensible error on first fail of the TOTP challenge.

fix(mfa-totp): On failed TOTP challlenge, yield sensible error

---

README.md

Add in a clear acknowledgement of the work done by D2L from the original project (Brightspace/bmx).
The project is missing a clear indication that D2L was the sole developer of bmx before modifications were made by members of Arctic Wolf (@rtkjbeverly). The project wasn't forked when it was originally experimented with during a hackathon, and until now it hasn't been noticed that the project was missing acknowledgements of this.
This adds in acknowledgements of this, but isn't complete.

docs(acknowledge): Missing acknowledgement of D2L

---

README.md

Missing link to the GitHub repository.

docs(badlink): Missing link to GitHub repository

---

.github/workflows/main.yml

This simplifies the trigger globs for the build workflow, to remove the duplication of go file type triggers. 
This was setup as a workaround for issues with globs in GitHub Actions that was encountered in beta/preview, and has been resolved.
Additionally bazel resources and go dependency files have been added to this list of available triggers.

build(ghactions): Simplify the action trigger globs

---

console.go
console/ConsoleReader.go
mocks/consoleReader.go
saml/identityProviders/okta/okta.go

Moves the message prompt for an option select into `Option`.
The message prompt is a component of the option itself, giving context to the choice. This change makes it easier to handle different models of input such as AppleScript in MacOS.

refactor(console): Move message prompt for option into Option method

---

saml/identityProviders/okta/file/oktaSession.go

Replace usage of sessions filename with a constant.
This matches the similar approach used for config and project file names. Additionally this makes it easier to change the name of the sessions file when wanting to experiment with bmx without impacting existing sessions.

refactor(sessions): Use constant for sessions filename

---

saml/serviceProviders/aws/provider.go

Remove the unused pickRole functions that was missed in 123c230e38aca2e9bf3abb704367823964b802cc.
The aws provider is no longer responsible for identifying the SAML role. This responsibility is now managed by the caller, and is passed into the provider itself.

refactor(aws): Remove the unused pickRoles function

---

console/ConsoleReader.go
saml/identityProviders/okta/okta.go

The TOTP code sent to Okta cannot have trailing whitespace or it will fail to verify.
`ReadLine` does not trim trailing whitespace from inputs. For the console case this doesn't happen often, but for other input devices there may be trailing whitespace. ReadLine itself shouldn't trim whitespace as that may be intended for the input.

fix(totp): TOTP code cannot have trailing whitespace

---

cmd/bmx/bmx.go
cmd/bmx/credential-process.go
console/ConsoleReader.go

Refactor console interface to better handle different input models.
The DefaultConsoleReader was built around working with terminal interfaces like zsh/bash/powershell. When support for `credential-process` was added, it was built with a narrow focus on usage from a console. This isn't always the case, and we need to be able to be flexible with where input is coming from, as `credential_process` isn't always invoked in the context of an interactive shell.
This lays the ground-work for supporting AppleScript in MacOS environments, which is the primary driver of this work.

refactor(console): Refactor console for multiple input modes

---

README.md
docs/input.md

Document the configuration enum `input` that controls input behaviour.
To accommodate some edge cases of `bmx` running in cases without access to a terminal, there is an input config that assists in controlling how input is sourced. This documents the options, and how they work in the system as a whole.

doc(input): Configuration enum to control input behaviour

---

.devcontainer/Dockerfile
.devcontainer/README.md
.devcontainer/devcontainer.json

Enables a bazel devcontainer environment that can be used for isolated development.
This enables development in a docker container, which allows for isolation from the current `bmx` installation on a developer machine. This can be useful when attempting to avoid sessions or config clashes with already configured environments.
Bazel buildtools like buildifier and buildozer have been installed on the machine. The list of tools is in no way complete.

build(devcontainers): Support devcontainer environments for development

---

LICENSE

Add Arctic Wolf Networks to the repository license to reflect code changes by AWN.
The project license remains the same, but the attribution for work done by Arctic Wolf is added to the root license. 
The file headers in all cases have not been updated as part of this, as that should be done separately. My understanding is that the license headers are only a recommendation, and not a requirement of license. However as this is in a copyright realm, I'm erring on the side of absurd levels of caution.

legal(license): Add AWN to license notice

---

print.go

If `print` cannot assume a role, then error instead of attempting to print invalid credentials.
This resolves the issue where if the `AssumeRole` cannot be assumed with the permissions of the AWS SSO Role, then it will attempt to print `nil` credentials, resulting in a segfault (`panic: runtime error: invalid memory address or nil pointer dereference`). This can reproduced by removing all policies from an SSO role, resulting in `AssumeRole` failing on permission denied.

fix(print): Segment fault if cannot assume role

---

console/AppleScript.go

AppleScript prompts do not clearly indicate that they are from BMX, raising suspicions.
This add BMX to the AppleScript dialog box titles to ensure that users are aware of the context behind the prompt.
This has shown up when individuals open IntelliJ, and are suddenly prompted for their Okta password with no context behind what script/utility is doing the prompt. Individuals with context of the prompt, may understand that it is done by BMX, but this conditions users to input credentials into unknown/unclear prompts. We'd like to avoid that as much as possible.

fix(applescript): AppleScript prompts can raise concerns

---

BUILD
cmd/bmx/BUILD.bazel
cmd/bmx/logout.go
login.go
saml/identityProviders/okta/file/oktaSession.go
saml/identityProviders/okta/mocks/mocks.go
saml/identityProviders/okta/okta.go

Introduce a `logout` command for clearing the sessions file.
This introduces a `logout` command to have a managed way of clearing out the `sessions` file. There are some edge cases, where an invalid token (or soon to be expired token) is used to communicate with Okta. The solution at present is to clear or delete the sessions file (`~/.bmx/sessions`).
The `logout` command adds a more managed way of doing this, till the exact cause of this issue can be resolved.

feat(logout): Clear stored sessions

---

saml/identityProviders/okta/file/oktaSession.go

Reduce duplicate construction of filepaths & writing to sessions files
This reduces the amount of duplication with generating the filepath for the sessions file, and consolidating the writing of the session file into a single method.
---
This is a minor refactoring, but I think some of the code in this space could be refactored about to be less reliant on the Okta integration. As I investigate the stale okta token issue, I'll explore this some more.

refactor(sessions): Reduce code duplication on sessions

---

saml/identityProviders/okta/file/oktaSession.go
write.go

This change makes sure that the `~/.bmx/sessions` and `~/.aws/credentials` files are written with `0600` permissions, preventing anyone but the owner from reading the files contents.

fix(sessions): Files with sensitive data should be written with 0600 permissions

---

cmd/bmx/bmx_default.go

**Description:** Rather than check for the ability to create a tty
connection and failing if we can't, continue as if we have one. In the
case where we have a valid session, we don't need the tty, so the
credential-process command will continue to work. If we need to use the
tty (because no valid session), we already are raising an error, so let
it fail then.
**Testing:** `bazel test //...` and manually testing locally

fix(credential-processs): Remove initial tty available check

---

CONTRIBUTING.md

Touchup the contribution policy to clarify how members of AWN (rtkwlf) should contribute to the repository.
This clarifies that for AWN members the internal guidelines for making changes to this repository apply (defaulting to using branches on the repository rather than forking), as well as our internal ticketing system should be used instead of GitHub actions.
Individuals external to the organization can make use of GitHub Issues for bug reports, and forking the repository to make changes.

docs(contrib): Touchups to internal instructions

---

config/loadConfig.go
console/AppleScript.go
vendor/github.com/andybrewer/mack/dialog.go

Support empty string defaults for the AppleScript dialog boxes.
This resolves an issue where if the `Answer` field was set as the empty string, it would no longer show the textbox. This allows a textbox-always handling for empty string answers, to ensure the textbox exists. As we don't leverage the dialog for confirmation windows, this is sufficient to handle out input case.
Confirmed working by testing locally with the AppleScript base cases (push/totp, no username, etc).
Additionally the location of the config file is now using the `projectFileName` constant.

fix(applescript): Support empty string default
